id: P29D39AC1
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1GS60877
  instance_id: http://purl.bdrc.io/resource/IE1GS60877
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - རྫོགས་པ་ཆེན་པོ་ངལ་གསོ་སྐོར་གསུམ།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P1583
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    fe39d920f9ab43188b5ac3268807c20d:
      title: པོད ༡་རྫོགས་པ་ཆེན་པོ་ངལ་གསོ་སྐོར་གསུམ
      volume_number: 1
      base_file: UT1GS60877_I1GS60879_0000.txt
      reference: http://purl.bdrc.io/resource/VL6B749D021CBE71DE
      image_group: I1GS60879
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW1GS60877
  - http://purl.bdrc.io/resource/W1GS60877
  ocr_software: Namsel
created_at: '2021-12-22T10:28:08.561034'
last_modified_at: '2021-12-22T10:28:08.561041'
statistics:
  total_words: 361687
  total_non_words: 40283
quality:
  non_words_ratio: 0.11
